default: &default
  adapter: mysql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  min_messages: warning
  username: root
  password: dummy

development:
  <<: *default
  database: db_tress_development

test:
  <<: *default
  database: db_tress_development
